pipeline:
  name: demo-pipeline-0204
  identifier: demopipeline0204
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubharness2103
        repoName: spring-petclinic
        build: <+input>
  stages:
    - stage:
        name: build-0204
        identifier: build0204
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.8.6-openjdk-17
                    shell: Sh
                    command: mvn clean install
                    privileged: true
          sharedPaths:
            - /root/.m2/repository/
          buildIntelligence:
            enabled: false
